// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6wKvM7TqJvRrrtnWSl2jA7CB6vEmg50c',
    appId: '1:908072550200:web:b4781792bdca9da2fb4bcd',
    messagingSenderId: '908072550200',
    projectId: 'hccatamarca-63eb3',
    authDomain: 'hccatamarca-63eb3.firebaseapp.com',
    storageBucket: 'hccatamarca-63eb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DJwrhuRCXTUP7LQJVIRFSp2QcQiU2TE',
    appId: '1:908072550200:android:dbf2f3d9b50e57c0fb4bcd',
    messagingSenderId: '908072550200',
    projectId: 'hccatamarca-63eb3',
    storageBucket: 'hccatamarca-63eb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzqNUi3BdqHECadrkT4JsrsjfNC2_xyDQ',
    appId: '1:908072550200:ios:5f84cb4bf18835dffb4bcd',
    messagingSenderId: '908072550200',
    projectId: 'hccatamarca-63eb3',
    storageBucket: 'hccatamarca-63eb3.firebasestorage.app',
    iosBundleId: 'com.example.hcCatamarca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzqNUi3BdqHECadrkT4JsrsjfNC2_xyDQ',
    appId: '1:908072550200:ios:5f84cb4bf18835dffb4bcd',
    messagingSenderId: '908072550200',
    projectId: 'hccatamarca-63eb3',
    storageBucket: 'hccatamarca-63eb3.firebasestorage.app',
    iosBundleId: 'com.example.hcCatamarca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6wKvM7TqJvRrrtnWSl2jA7CB6vEmg50c',
    appId: '1:908072550200:web:61326d72568693a5fb4bcd',
    messagingSenderId: '908072550200',
    projectId: 'hccatamarca-63eb3',
    authDomain: 'hccatamarca-63eb3.firebaseapp.com',
    storageBucket: 'hccatamarca-63eb3.firebasestorage.app',
  );
}
